version: '3'

services:
  php:
    build:
      args:
        version: ${PHP_VERSION}
      context: .
      dockerfile: ./docker/php/Dockerfile.test
    depends_on:
      - elastic
    stdin_open: true
    tty: true
  elastic:
    build:
      args:
        version: ${ELASTIC_VERSION}
      context: ./docker/elastic
